# Numpy

In [1]:
import numpy as np

### 2.6. Uso de condiciones para modificar elementos

In [2]:
# Crea un array 5x5 con números del 10 al 34
array6 = np.arange(10, 35).reshape(5, 5)
print("Array 5x5:\n", array6)


Array 5x5:
 [[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]


In [3]:
# Reemplaza los valores mayores que 20 por 0
array_modificado = np.where(array6 > 20, 0, array6)
print("\nArray después de reemplazar valores mayores que 20 por 0:\n", array_modificado)


Array después de reemplazar valores mayores que 20 por 0:
 [[10 11 12 13 14]
 [15 16 17 18 19]
 [20  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]


In [4]:
# Extrae los elementos menores que 15
elementos_menores_que_15 = array6[array6 < 15]
print("\nElementos menores que 15:", elementos_menores_que_15)


Elementos menores que 15: [10 11 12 13 14]


In [5]:
# Cambia los valores menores que 18 por -1
array6[array6 < 18] = -1
print("\nArray después de cambiar los valores menores que 18 por -1:\n", array6)


Array después de cambiar los valores menores que 18 por -1:
 [[-1 -1 -1 -1 -1]
 [-1 -1 -1 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]


### 2.7. Indexación con arrays booleanos

In [6]:
# Crea un array 3x4 con valores aleatorios enteros entre 0 y 9
array7 = np.random.randint(0, 10, size=(3, 4))
print("Array 3x4 con valores aleatorios:\n", array7)

Array 3x4 con valores aleatorios:
 [[0 7 9 5]
 [6 4 8 6]
 [4 0 0 3]]


In [7]:
# Crea una máscara booleana para los elementos mayores que 5
mascara_mayores_que_5 = array7 > 5
print("\nMáscara booleana (valores > 5):\n", mascara_mayores_que_5)


Máscara booleana (valores > 5):
 [[False  True  True False]
 [ True False  True  True]
 [False False False False]]


In [8]:
# Usando la máscara, extrae los elementos mayores que 5
elementos_mayores_que_5 = array7[mascara_mayores_que_5]
print("\nElementos mayores que 5:", elementos_mayores_que_5)


Elementos mayores que 5: [7 9 6 8 6]


In [10]:
# Cambia todos los valores mayores que 5 por -2
array7[array7 > 5] = -2
print("\nArray después de cambiar valores mayores que 5 por -2:\n", array7)


Array después de cambiar valores mayores que 5 por -2:
 [[ 0 -2 -2  5]
 [-2  4 -2 -2]
 [ 4  0  0  3]]


### 2.8. Indexación por posiciones específicas con np.ix_

In [11]:
# Crea un array 5x5 con números del 0 al 24
array8 = np.arange(25).reshape(5, 5)
print("Array 5x5:\n", array8)

Array 5x5:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [12]:
# Usa np.ix_ para obtener una submatriz usando filas y columnas específicas
filas = [1, 3]
columnas = [0, 2, 4]
submatriz = array8[np.ix_(filas, columnas)]
print("\nSubmatriz usando np.ix_:\n", submatriz)


Submatriz usando np.ix_:
 [[ 5  7  9]
 [15 17 19]]


### 2.9. Obtener elementos alternos en una fila o columna

In [13]:
# Crea un array de 6x6 con números del 10 al 45
array9 = np.arange(10, 46).reshape(6, 6)
print("Array 6x6:\n", array9)

Array 6x6:
 [[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]
 [34 35 36 37 38 39]
 [40 41 42 43 44 45]]


In [14]:
# Extrae los elementos de la primera fila de forma alterna
elementos_alternos_fila = array9[0, ::2]
print("\nElementos alternos en la primera fila:", elementos_alternos_fila)


Elementos alternos en la primera fila: [10 12 14]


In [15]:
# Extrae los elementos de la segunda columna de forma alterna
elementos_alternos_columna = array9[::2, 1]
print("\nElementos alternos en la segunda columna:", elementos_alternos_columna)


Elementos alternos en la segunda columna: [11 23 35]


### 2.10. Trabajar con índices negativos

In [16]:
# Crea un array de 4x4 con números del 1 al 16
array10 = np.arange(1, 17).reshape(4, 4)
print("Array 4x4:\n", array10)

Array 4x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [17]:
# Obtén los elementos de la última fila usando índices negativos
ultima_fila = array10[-1, :]
print("\nÚltima fila usando índices negativos:", ultima_fila)


Última fila usando índices negativos: [13 14 15 16]


In [18]:
# Obtén los elementos de las dos últimas columnas usando índices negativos
ultimas_columnas = array10[:, -2:]
print("\nDos últimas columnas usando índices negativos:\n", ultimas_columnas)


Dos últimas columnas usando índices negativos:
 [[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
