# Numpy

In [1]:
import numpy as np

## 4. Matrices y productos matriciales

### 4.1. Creación de matrices y acceso a elementos

In [2]:
# Crea una matriz 3x3 con números del 1 al 9
matriz1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
# Accede al elemento en la fila 2, columna 3
elemento = matriz1[1, 2]  # Recuerda que los índices empiezan en 0
print("Elemento en fila 2, columna 3:", elemento)

Elemento en fila 2, columna 3: 6


In [4]:
# Accede a la segunda fila completa
fila2 = matriz1[1, :]
print("Segunda fila completa:", fila2)

Segunda fila completa: [4 5 6]


In [5]:
# Accede a la tercera columna completa
columna3 = matriz1[:, 2]
print("Tercera columna completa:", columna3)

Tercera columna completa: [3 6 9]


### 4.2. Transposición de matrices

In [6]:
# Crea una matriz de 2x3
matriz2 = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
# Transpone la matriz
transpuesta = np.transpose(matriz2)
print("Matriz original:\n", matriz2)
print("\nMatriz transpuesta:\n", transpuesta)

Matriz original:
 [[1 2 3]
 [4 5 6]]

Matriz transpuesta:
 [[1 4]
 [2 5]
 [3 6]]


### 4.3. Multiplicación de matrices (producto matricial)

In [8]:
# Crea dos matrices 2x2
matriz3 = np.array([[1, 2], [3, 4]])
matriz4 = np.array([[5, 6], [7, 8]])

In [9]:
# Producto matricial de las dos matrices
producto_matrices = np.dot(matriz3, matriz4)
print("Producto matricial de 2x2:\n", producto_matrices)

Producto matricial de 2x2:
 [[19 22]
 [43 50]]


In [10]:
# Alternativa con el operador @
producto_matrices2 = matriz3 @ matriz4
print("\nProducto matricial usando @:\n", producto_matrices2)


Producto matricial usando @:
 [[19 22]
 [43 50]]


### 4.4. Multiplicación de matrices y vectores

In [11]:
# Crea una matriz 3x3
matriz5 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [12]:
# Crea un vector columna de 3 elementos
vector = np.array([1, 2, 3])

In [13]:
# Producto de la matriz 3x3 con el vector
producto_matriz_vector = np.dot(matriz5, vector)
print("Producto de matriz 3x3 y vector columna:", producto_matriz_vector)


Producto de matriz 3x3 y vector columna: [14 32 50]


### 4.5. Determinante de una matriz

In [15]:
# Crea una matriz 3x3
matriz6 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [16]:
# Calcula el determinante de la matriz
determinante = np.linalg.det(matriz6)
print("Determinante de la matriz 3x3:", determinante)

Determinante de la matriz 3x3: 0.0
