# Numpy

## 1. Crear arrays y operaciones básicas

In [1]:
import numpy as np

In [2]:
# Crea un array de 1D con números del 0 al 9
array1 = np.arange(10)
print("Array de 0 a 9:", array1)


Array de 0 a 9: [0 1 2 3 4 5 6 7 8 9]


In [3]:
# Crea un array de 3x3 con números aleatorios
array2 = np.random.random((3, 3))
print("\nArray 3x3 aleatorio:\n", array2)


Array 3x3 aleatorio:
 [[0.61544051 0.2205225  0.12592603]
 [0.17093532 0.16140241 0.99585496]
 [0.6106125  0.71978001 0.5340893 ]]


In [4]:
# Suma 5 a todos los elementos del array
array_sumado = array1 + 5
print("\nArray sumado en 5:", array_sumado)


Array sumado en 5: [ 5  6  7  8  9 10 11 12 13 14]


### 1.1 Crear un array con valores específicos

In [5]:
# Crea un array de números enteros del 10 al 49
array1 = np.arange(10, 50)
print("Array de 10 a 49:", array1)

Array de 10 a 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
# Invierte el array (de modo que los elementos estén en orden inverso)
array_invertido = array1[::-1]
print("\nArray invertido:", array_invertido)



Array invertido: [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### 1.2. Array de valores flotantes

In [7]:
# Crea un array de 5x5 con valores aleatorios entre 0 y 1
array2 = np.random.rand(5, 5)
print("Array 5x5 con valores aleatorios entre 0 y 1:\n", array2)

Array 5x5 con valores aleatorios entre 0 y 1:
 [[0.45787123 0.42665851 0.64636096 0.24591299 0.62588451]
 [0.8112024  0.4659202  0.82705473 0.76985171 0.8858964 ]
 [0.9995194  0.80133125 0.44646851 0.67148    0.89006682]
 [0.37705534 0.59069848 0.72466262 0.1241144  0.55595635]
 [0.21522318 0.18816784 0.12209105 0.99104417 0.76430648]]


In [8]:
# Multiplica el array por 10
array_multiplicado = array2 * 10
print("\nArray multiplicado por 10:\n", array_multiplicado)


Array multiplicado por 10:
 [[4.57871233 4.26658507 6.46360964 2.4591299  6.25884508]
 [8.11202402 4.65920197 8.27054735 7.69851708 8.858964  ]
 [9.99519405 8.01331247 4.46468512 6.71480004 8.90066817]
 [3.77055337 5.90698485 7.24662621 1.24114404 5.55956348]
 [2.15223178 1.88167844 1.22091046 9.91044165 7.64306483]]


### 1.3. Array de un solo valor

In [9]:
# Crea un array de 6x6 con todos los valores iguales a 7
array3 = np.full((6, 6), 7)
print("Array 6x6 lleno de 7s:\n", array3)

Array 6x6 lleno de 7s:
 [[7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]]


In [10]:
# Eleva cada valor del array al cuadrado
array_cuadrado = np.power(array3, 2)
print("\nArray elevado al cuadrado:\n", array_cuadrado)


Array elevado al cuadrado:
 [[49 49 49 49 49 49]
 [49 49 49 49 49 49]
 [49 49 49 49 49 49]
 [49 49 49 49 49 49]
 [49 49 49 49 49 49]
 [49 49 49 49 49 49]]


### 1.4. Crear un array identidad

In [11]:
# Crea una matriz identidad de 4x4
matriz_identidad = np.eye(4)
print("Matriz identidad 4x4:\n", matriz_identidad)

Matriz identidad 4x4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
# Multiplica la matriz identidad por 3
matriz_identidad_mult = matriz_identidad * 3
print("\nMatriz identidad multiplicada por 3:\n", matriz_identidad_mult)


Matriz identidad multiplicada por 3:
 [[3. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 3.]]


### 1.5. Crear arrays con funciones matemáticas

In [13]:
# Crea un array con 20 valores entre 0 y 2π
array_angular = np.linspace(0, 2 * np.pi, 20)
print("Array con 20 valores entre 0 y 2π:\n", array_angular)

Array con 20 valores entre 0 y 2π:
 [0.         0.33069396 0.66138793 0.99208189 1.32277585 1.65346982
 1.98416378 2.31485774 2.64555171 2.97624567 3.30693964 3.6376336
 3.96832756 4.29902153 4.62971549 4.96040945 5.29110342 5.62179738
 5.95249134 6.28318531]


In [15]:
# Calcula el seno de cada valor
array_seno = np.sin(array_angular)
print("\nSeno de cada valor:\n", array_seno)


Seno de cada valor:
 [ 0.00000000e+00  3.24699469e-01  6.14212713e-01  8.37166478e-01
  9.69400266e-01  9.96584493e-01  9.15773327e-01  7.35723911e-01
  4.75947393e-01  1.64594590e-01 -1.64594590e-01 -4.75947393e-01
 -7.35723911e-01 -9.15773327e-01 -9.96584493e-01 -9.69400266e-01
 -8.37166478e-01 -6.14212713e-01 -3.24699469e-01 -2.44929360e-16]
