# Numpy

In [1]:
import numpy as np

## 5. Operaciones de álgebra lineal

### 5.6. Determinante de una matriz

In [2]:
# Crea una matriz 3x3
matriz2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
# Calcula el determinante
determinante = np.linalg.det(matriz2)
print("Determinante de la matriz 3x3:", determinante)

Determinante de la matriz 3x3: 0.0


### 5.7. Inversa de una matriz

In [4]:
# Define una matriz 2x2 invertible
matriz3 = np.array([[4, 7], [2, 6]])

In [5]:
# Calcula la inversa de la matriz
inversa = np.linalg.inv(matriz3)
print("Matriz inversa:\n", inversa)

Matriz inversa:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


### 5.8. Factorización LU

In [9]:
from scipy.linalg import lu

In [10]:
# Crea una matriz 3x3
matriz4 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])

In [11]:
# Descomposición LU
P, L, U = lu(matriz4)
print("Matriz P:\n", P)
print("\nMatriz L:\n", L)
print("\nMatriz U:\n", U)

Matriz P:
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

Matriz L:
 [[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]

Matriz U:
 [[7.         8.         0.        ]
 [0.         0.85714286 3.        ]
 [0.         0.         4.5       ]]


### 5.9. Singular Value Decomposition (SVD)

In [12]:
# Crea una matriz 2x3
matriz5 = np.array([[1, 0, 0], [0, 1, 0]])

In [13]:
# Descomposición SVD
U, S, Vt = np.linalg.svd(matriz5)
print("Matriz U:\n", U)
print("\nValores singulares (S):", S)
print("\nMatriz Vt:\n", Vt)

Matriz U:
 [[1. 0.]
 [0. 1.]]

Valores singulares (S): [1. 1.]

Matriz Vt:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 5.10. Matriz de Gram

In [14]:
# Define un conjunto de vectores como filas de una matriz
vectores = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [15]:
# Matriz de Gram: G = A^T A
matriz_gram = np.dot(vectores.T, vectores)
print("Matriz de Gram:\n", matriz_gram)

Matriz de Gram:
 [[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]
