# Numpy

In [1]:
import numpy as np

## 1. Crear arrays y operaciones básicas

### 1.6. Generar arrays vacíos o inicializados

In [2]:
# Crea un array vacío de 4x4
array_vacio = np.empty((4, 4))
print("Array vacío 4x4:\n", array_vacio)

Array vacío 4x4:
 [[1.01931583e-316 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [3]:
# Crea un array de ceros de tamaño 3x5
array_ceros = np.zeros((3, 5))
print("\nArray de ceros 3x5:\n", array_ceros)


Array de ceros 3x5:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
# Crea un array de unos de tamaño 2x6
array_unos = np.ones((2, 6))
print("\nArray de unos 2x6:\n", array_unos)


Array de unos 2x6:
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


### 1.7. Operaciones aritméticas básicas

In [5]:
# Crea un array de 1D con 5 valores entre 1 y 5
array4 = np.array([1, 2, 3, 4, 5])

In [6]:
# Suma 3 a cada elemento del array
array_suma = array4 + 3
print("Array después de sumar 3:", array_suma)

Array después de sumar 3: [4 5 6 7 8]


In [7]:
# Multiplica cada elemento del array por 2
array_multiplica = array4 * 2
print("\nArray después de multiplicar por 2:", array_multiplica)


Array después de multiplicar por 2: [ 2  4  6  8 10]


In [15]:
# Eleva al cubo cada elemento del array
array_cubo = array4 ** 3
print("\nArray elevado al cubo:", array_cubo)


Array elevado al cubo: [  1   8  27  64 125]


### 1.8. Concatenación y apilamiento de arrays

In [16]:
# Crea dos arrays de 1D con números del 1 al 3 y del 4 al 6
array5 = np.array([1, 2, 3])
array6 = np.array([4, 5, 6])

In [17]:
# Concatenar los dos arrays
array_concatenado = np.concatenate((array5, array6))
print("Array concatenado:", array_concatenado)

Array concatenado: [1 2 3 4 5 6]


In [18]:
# Crea dos arrays 2x2
array7 = np.array([[1, 2], [3, 4]])
array8 = np.array([[5, 6], [7, 8]])

In [19]:
# Apila los dos arrays verticalmente
array_apilado_v = np.vstack((array7, array8))
print("\nArrays apilados verticalmente:\n", array_apilado_v)


Arrays apilados verticalmente:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [20]:
# Apila los dos arrays horizontalmente
array_apilado_h = np.hstack((array7, array8))
print("\nArrays apilados horizontalmente:\n", array_apilado_h)



Arrays apilados horizontalmente:
 [[1 2 5 6]
 [3 4 7 8]]


### 1.9. Array booleano y filtros

In [22]:
# Crea un array de 1D con valores enteros del 10 al 19
array9 = np.arange(10, 20)

In [23]:
# Crea una máscara booleana para filtrar los elementos mayores que 15
mascara = array9 > 15
print("Máscara booleana:", mascara)

Máscara booleana: [False False False False False False  True  True  True  True]


In [24]:
# Aplica la máscara para filtrar el array
array_filtrado = array9[mascara]
print("\nArray filtrado (valores > 15):", array_filtrado)


Array filtrado (valores > 15): [16 17 18 19]


### 1.10. Generar arrays de números aleatorios

In [25]:
# Crea un array de 4x4 con números aleatorios entre 0 y 1
array_aleatorio = np.random.random((4, 4))
print("Array 4x4 con valores aleatorios entre 0 y 1:\n", array_aleatorio)


Array 4x4 con valores aleatorios entre 0 y 1:
 [[0.98875394 0.67293092 0.39926068 0.77686005]
 [0.78939513 0.31245394 0.92318046 0.70450045]
 [0.05457321 0.53400181 0.97142413 0.7139485 ]
 [0.43488343 0.21581327 0.38638496 0.67898633]]


In [26]:
#Aray de 5 elementos con números enteros aleatorios entre 50 y 100
array_enteros_aleatorios = np.random.randint(50, 100, size=5)
print("\nArray con enteros aleatorios entre 50 y 100:", array_enteros_aleatorios)


Array con enteros aleatorios entre 50 y 100: [66 72 98 73 58]
