# Numpy

### 2.1. Extraer subarrays y modificar elementos

In [1]:
import numpy as np
# Crea un array 5x5 con números del 0 al 24
array1 = np.arange(25).reshape(5, 5)
print("Array 5x5:\n", array1)

Array 5x5:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [2]:
# Extrae las primeras tres filas y las primeras tres columnas
sub_array1 = array1[:3, :3]
print("\nSubarray con las primeras 3 filas y columnas:\n", sub_array1)



Subarray con las primeras 3 filas y columnas:
 [[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]


In [3]:
# Cambia el valor del elemento en la posición [1, 2] por 99
array1[1, 2] = 99
print("\nArray después de cambiar el valor en [1, 2]:\n", array1)


Array después de cambiar el valor en [1, 2]:
 [[ 0  1  2  3  4]
 [ 5  6 99  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### 2.2. Obtener elementos en posiciones específicas

In [4]:
# Crea un array 6x6 con números del 0 al 35
array2 = np.arange(36).reshape(6, 6)
print("Array 6x6:\n", array2)

Array 6x6:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [5]:
# Obtén los elementos de la primera fila
primera_fila = array2[0, :]
print("\nPrimera fila:", primera_fila)


Primera fila: [0 1 2 3 4 5]


In [6]:
# Obtén los elementos de la última columna
ultima_columna = array2[:, -1]
print("\nÚltima columna:", ultima_columna)


Última columna: [ 5 11 17 23 29 35]


In [7]:
# Obtén los elementos de las posiciones (1, 1), (2, 2) y (3, 3)
elementos_diagonal = array2[[1, 2, 3], [1, 2, 3]]
print("\nElementos en la diagonal en posiciones específicas (1,1), (2,2), (3,3):", elementos_diagonal)



Elementos en la diagonal en posiciones específicas (1,1), (2,2), (3,3): [ 7 14 21]


### 2.3. Slicing avanzado en arrays 3D

In [8]:
# Crea un array 3x3x3 con números del 0 al 26
array3 = np.arange(27).reshape(3, 3, 3)
print("Array 3D 3x3x3:\n", array3)

Array 3D 3x3x3:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [9]:
# Obtén el primer "bloque" 2D del array 3D
bloque_2d = array3[0, :, :]
print("\nPrimer bloque 2D del array 3D:\n", bloque_2d)



Primer bloque 2D del array 3D:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
# Obtén los elementos del último "bloque" 2D en la segunda fila
segunda_fila_bloque = array3[-1, 1, :]
print("\nSegunda fila del último bloque 2D:\n", segunda_fila_bloque)


Segunda fila del último bloque 2D:
 [21 22 23]


In [11]:
# Obtén los elementos en la posición [0, 1, 2] y [2, 1, 1]
elementos_especificos = array3[[0, 2], [1, 1], [2, 1]]
print("\nElementos específicos [0,1,2] y [2,1,1]:", elementos_especificos)



Elementos específicos [0,1,2] y [2,1,1]: [ 5 22]


### 2.4. Inversión y manipulación de subarrays

In [12]:
# Crea un array de 1D con números del 1 al 10
array4 = np.arange(1, 11)
print("Array 1D original:", array4)

Array 1D original: [ 1  2  3  4  5  6  7  8  9 10]


In [13]:
# Invierte el array
array_invertido = array4[::-1]
print("\nArray invertido:", array_invertido)


Array invertido: [10  9  8  7  6  5  4  3  2  1]


In [14]:
# Extrae los elementos en posiciones impares
elementos_impares = array4[1::2]
print("\nElementos en posiciones impares:", elementos_impares)


Elementos en posiciones impares: [ 2  4  6  8 10]


In [16]:
# Cambia los elementos del array en las posiciones 2 a 5 (sin incluir 5) a -1
array4[2:5] = -1
print("\nArray después de cambiar posiciones 2 a 5:\n", array4)


Array después de cambiar posiciones 2 a 5:
 [ 1  2 -1 -1 -1  6  7  8  9 10]


### 2.5. Slicing de columnas y filas específicas

In [17]:
# Crea un array 4x5 con números del 0 al 19
array5 = np.arange(20).reshape(4, 5)
print("Array 4x5:\n", array5)

Array 4x5:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [18]:
# Extrae la tercera columna
tercera_columna = array5[:, 2]
print("\nTercera columna:", tercera_columna)


Tercera columna: [ 2  7 12 17]


In [19]:
# Extrae las filas 1 y 3
filas_1_y_3 = array5[[1, 3], :]
print("\nFilas 1 y 3:\n", filas_1_y_3)


Filas 1 y 3:
 [[ 5  6  7  8  9]
 [15 16 17 18 19]]


In [20]:
# Extrae las primeras dos filas y las columnas 2 y 3
sub_array2 = array5[:2, 2:4]
print("\nSub-array de las dos primeras filas y columnas 2 y 3:\n", sub_array2)


Sub-array de las dos primeras filas y columnas 2 y 3:
 [[2 3]
 [7 8]]
