# Numpy

In [1]:
import numpy as np

## 4. Matrices y productos matriciales

### 4.6. Inversa de una matriz

In [2]:
# Crea una matriz 2x2 invertible
matriz7 = np.array([[4, 7], [2, 6]])

In [3]:
# Calcula la inversa de la matriz
inversa = np.linalg.inv(matriz7)
print("Matriz inversa:\n", inversa)

Matriz inversa:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


### 4.7. Traza de una matriz

In [4]:
# Crea una matriz 3x3
matriz8 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [5]:
# Calcula la traza (suma de los elementos diagonales)
traza = np.trace(matriz8)
print("Traza de la matriz 3x3:", traza)


Traza de la matriz 3x3: 15


### 4.8. Autovalores y autovectores

In [6]:
# Crea una matriz 2x2
matriz9 = np.array([[4, -2], [1, 1]])

In [7]:
# Calcula los autovalores y autovectores
autovalores, autovectores = np.linalg.eig(matriz9)
print("Autovalores:", autovalores)
print("\nAutovectores:\n", autovectores)

Autovalores: [3. 2.]

Autovectores:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


### 4.9. Suma de matrices

In [8]:
# Crea dos matrices de 3x3
matriz10 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz11 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

In [9]:
# Suma de las matrices
suma_matrices = np.add(matriz10, matriz11)
print("Suma de las dos matrices:\n", suma_matrices)

Suma de las dos matrices:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


### 4.10. Multiplicación elemento a elemento de matrices

In [10]:
# Multiplicación elemento a elemento
multiplicacion_elemento = np.multiply(matriz10, matriz11)
print("Multiplicación elemento a elemento de las matrices:\n", multiplicacion_elemento)


Multiplicación elemento a elemento de las matrices:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
