# Numpy

In [1]:
import numpy as np

## 3. Operaciones matemáticas sobre arrays

### 3.1. Suma y resta de arrays

In [2]:
# Crea dos arrays de 2x3 con números del 1 al 6 y del 7 al 12
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

In [3]:
# Suma de los dos arrays
suma = np.add(array1, array2)
print("Suma de los arrays:\n", suma)

Suma de los arrays:
 [[ 8 10 12]
 [14 16 18]]


In [4]:
# Resta de los dos arrays
resta = np.subtract(array1, array2)
print("\nResta de los arrays:\n", resta)


Resta de los arrays:
 [[-6 -6 -6]
 [-6 -6 -6]]


### 3.2. Multiplicación y división de arrays

In [5]:
# Multiplicación elemento a elemento
multiplicacion = np.multiply(array1, array2)
print("\nMultiplicación elemento a elemento:\n", multiplicacion)


Multiplicación elemento a elemento:
 [[ 7 16 27]
 [40 55 72]]


In [6]:
# División elemento a elemento
division = np.divide(array2, array1)
print("\nDivisión elemento a elemento:\n", division)



División elemento a elemento:
 [[7.  4.  3. ]
 [2.5 2.2 2. ]]


### 3.3. Producto de matrices

In [7]:
# Crea dos matrices 3x3
matriz1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])


In [8]:
# Producto matricial
producto_matricial = np.dot(matriz1, matriz2)
print("Producto matricial de 3x3:\n", producto_matricial)

Producto matricial de 3x3:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [9]:
# Producto matricial usando @ (alternativa)
producto_matricial2 = matriz1 @ matriz2
print("\nProducto matricial usando @:\n", producto_matricial2)


Producto matricial usando @:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


### 3.4. Potencia y raíz cuadrada de arrays

In [10]:
# Crea un array de 1x4 con números del 1 al 4
array3 = np.array([1, 2, 3, 4])

In [11]:
# Elevar al cuadrado cada elemento del array
cuadrado = np.power(array3, 2)
print("Array elevado al cuadrado:", cuadrado)

Array elevado al cuadrado: [ 1  4  9 16]


In [12]:
# Calcula la raíz cuadrada de cada elemento del array
raiz_cuadrada = np.sqrt(array3)
print("\nRaíz cuadrada del array:", raiz_cuadrada)


Raíz cuadrada del array: [1.         1.41421356 1.73205081 2.        ]


### 3.5. Operaciones trigonométricas

In [13]:
# Crea un array de 4 elementos entre 0 y π
array4 = np.linspace(0, np.pi, 4)
print("Array con valores entre 0 y π:", array4)

Array con valores entre 0 y π: [0.         1.04719755 2.0943951  3.14159265]


In [14]:
# Calcula el seno de cada elemento
seno = np.sin(array4)
print("\nSeno de los valores en el array:", seno)


Seno de los valores en el array: [0.00000000e+00 8.66025404e-01 8.66025404e-01 1.22464680e-16]


In [15]:
# Calcula el coseno de cada elemento
coseno = np.cos(array4)
print("\nCoseno de los valores en el array:", coseno)


Coseno de los valores en el array: [ 1.   0.5 -0.5 -1. ]
