# Numpy

In [1]:
import numpy as np

## 3. Operaciones matemáticas sobre arrays

### 3.11. Transposición de matrices

In [2]:
# Crea una matriz 3x2
matriz3 = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
# Transpone la matriz
transpuesta = np.transpose(matriz3)
print("Matriz transpuesta:\n", transpuesta)

Matriz transpuesta:
 [[1 3 5]
 [2 4 6]]


### 3.12. Normalización de arrays

In [4]:
# Crea un array con 5 valores aleatorios entre 0 y 100
array11 = np.random.randint(0, 101, 5)
print("Array original:", array11)

Array original: [35 76 78  8 96]


In [5]:
# Normaliza el array (escala los valores para que estén entre 0 y 1)
array_normalizado = (array11 - np.min(array11)) / (np.max(array11) - np.min(array11))
print("\nArray normalizado:", array_normalizado)


Array normalizado: [0.30681818 0.77272727 0.79545455 0.         1.        ]


### 3.13. Operaciones con números complejos

In [6]:
# Crea un array de números complejos
array_complejo = np.array([1+2j, 3+4j, 5+6j])

In [7]:
# Calcula el valor absoluto de cada número complejo
absoluto_complejo = np.abs(array_complejo)
print("Valor absoluto de los números complejos:", absoluto_complejo)

Valor absoluto de los números complejos: [2.23606798 5.         7.81024968]


In [8]:
# Calcula el ángulo de fase de cada número complejo
angulo_fase = np.angle(array_complejo)
print("\nÁngulo de fase de los números complejos:", angulo_fase)


Ángulo de fase de los números complejos: [1.10714872 0.92729522 0.87605805]


### 3.14. Broadcasting: operaciones con arrays de diferente forma

In [9]:
# Crea un array 3x3 y un array 1x3
array12 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array13 = np.array([10, 20, 30])

In [10]:
# Suma el array de 1x3 a cada fila del array de 3x3 (broadcasting)
resultado_broadcasting = array12 + array13
print("Resultado del broadcasting:\n", resultado_broadcasting)

Resultado del broadcasting:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


### 3.15. Operaciones en el eje (axis) de arrays

In [11]:
# Crea un array 4x4 con números del 1 al 16
array14 = np.arange(1, 17).reshape(4, 4)
print("Array 4x4:\n", array14)

Array 4x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [12]:
# Suma de los elementos por fila (axis=1)
suma_filas = np.sum(array14, axis=1)
print("\nSuma por fila:", suma_filas)


Suma por fila: [10 26 42 58]


In [13]:
# Producto de los elementos por columna (axis=0)
producto_columnas = np.prod(array14, axis=0)
print("\nProducto por columna:", producto_columnas)


Producto por columna: [ 585 1680 3465 6144]
