# Numpy

In [1]:
import numpy as np

## 5. Operaciones de álgebra lineal

### 5.11. Exponencial de una matriz

In [3]:
from scipy.linalg import expm

In [4]:
# Define una matriz 2x2
matriz6 = np.array([[0, 1], [-1, 0]])

In [5]:
# Calcula la exponencial de la matriz
exp_matriz = expm(matriz6)
print("Exponencial de la matriz:\n", exp_matriz)

Exponencial de la matriz:
 [[ 0.54030231  0.84147098]
 [-0.84147098  0.54030231]]


### 5.12. Descomposición de Cholesky

In [6]:
# Crea una matriz simétrica y positiva definida
matriz7 = np.array([[4, 12], [12, 37]])

In [7]:
# Descomposición de Cholesky
L = np.linalg.cholesky(matriz7)
print("Matriz triangular inferior L:\n", L)

Matriz triangular inferior L:
 [[2. 0.]
 [6. 1.]]


### 5.13. Proyección de un vector sobre otro

In [8]:
# Crea dos vectores
v1 = np.array([3, 4])
v2 = np.array([1, 2])

In [9]:
# Proyección de v1 sobre v2
proyeccion = (np.dot(v1, v2) / np.dot(v2, v2)) * v2
print("Proyección de v1 sobre v2:", proyeccion)

Proyección de v1 sobre v2: [2.2 4.4]


### 5.14. Resolución de un sistema sobredeterminado

In [10]:
# Define una matriz A y un vector b
A = np.array([[1, 1], [1, 2], [1, 3]])
b = np.array([1, 2, 2])

In [11]:
# Soluciona el sistema utilizando mínimos cuadrados
x, residuo, rango, s = np.linalg.lstsq(A, b, rcond=None)
print("Solución del sistema sobredeterminado:", x)

Solución del sistema sobredeterminado: [0.66666667 0.5       ]


### 5.15. Descomposición QR

In [12]:
# Define una matriz 3x3
matriz8 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [13]:
# Descomposición QR
Q, R = np.linalg.qr(matriz8)
print("Matriz Q:\n", Q)
print("\nMatriz R:\n", R)

Matriz Q:
 [[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]

Matriz R:
 [[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]


### 5.16. Determinación del rango de una matriz

In [14]:
# Crea una matriz 3x3
matriz9 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 0]])

In [15]:
# Calcula el rango de la matriz
rango = np.linalg.matrix_rank(matriz9)
print("Rango de la matriz:", rango)

Rango de la matriz: 2


### 5.17. Condición de una matriz

In [16]:
# Define una matriz 2x2
matriz10 = np.array([[1, 2], [3, 4]])

In [17]:
# Calcula el número de condición de la matriz
condicion = np.linalg.cond(matriz10)
print("Número de condición de la matriz:", condicion)

Número de condición de la matriz: 14.933034373659268
