# Numpy

In [1]:
import numpy as np

## 4. Matrices y productos matriciales

### 4.11. Descomposición de matrices: SVD (Singular Value Decomposition)

In [2]:
# Crea una matriz 2x2
matriz12 = np.array([[3, 1], [1, 3]])

In [3]:
# Descomposición en valores singulares
U, S, V = np.linalg.svd(matriz12)

print("Matriz U:\n", U)
print("\nValores singulares (S):", S)
print("\nMatriz V:\n", V)


Matriz U:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Valores singulares (S): [4. 2.]

Matriz V:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


### 4.12. Resolución de sistemas de ecuaciones lineales

In [4]:
# Sistema de ecuaciones: Ax = b
# A es la matriz de coeficientes y b es el vector de resultados
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])

In [5]:
# Soluciona el sistema Ax = b
x = np.linalg.solve(A, b)
print("Solución del sistema de ecuaciones:", x)

Solución del sistema de ecuaciones: [2. 3.]


### 4.13. Matrices diagonales

In [9]:
# Crea dos matrices de 3x3
matriz10 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz11 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Suma de las matrices
suma_matrices = np.add(matriz10, matriz11)
print("Suma de las dos matrices:\n", suma_matrices)


Suma de las dos matrices:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


In [11]:
# Crea una matriz diagonal con elementos 1, 2 y 3
matriz_diagonal = np.diag([1, 2, 3])
print("Matriz diagonal:\n", matriz_diagonal)


Matriz diagonal:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [12]:
# Extrae la diagonal de una matriz 3x3
diagonal_extraida = np.diag(matriz10)
print("\nDiagonal extraída de una matriz 3x3:", diagonal_extraida)


Diagonal extraída de una matriz 3x3: [1 5 9]


### 4.14. Matrices de identidad y matrices nulas

In [13]:
# Crea una matriz identidad de 4x4
matriz_identidad = np.eye(4)
print("Matriz identidad 4x4:\n", matriz_identidad)

Matriz identidad 4x4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
# Crea una matriz nula de 3x3
matriz_nula = np.zeros((3, 3))
print("\nMatriz nula 3x3:\n", matriz_nula)


Matriz nula 3x3:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### 4.15. Producto Kronecker entre matrices

In [15]:
# Crea dos matrices pequeñas
matriz13 = np.array([[1, 2], [3, 4]])
matriz14 = np.array([[0, 5], [6, 7]])

In [16]:
# Producto Kronecker de las matrices
producto_kronecker = np.kron(matriz13, matriz14)
print("Producto Kronecker:\n", producto_kronecker)

Producto Kronecker:
 [[ 0  5  0 10]
 [ 6  7 12 14]
 [ 0 15  0 20]
 [18 21 24 28]]


### 4.16. Operaciones con bloques de matrices

In [18]:
# Crea una matriz 4x4
matriz15 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

In [19]:
# Extrae un bloque 2x2 desde la esquina superior izquierda
bloque = matriz15[0:2, 0:2]
print("Bloque 2x2 extraído:\n", bloque)

Bloque 2x2 extraído:
 [[1 2]
 [5 6]]


In [20]:
# Reemplaza un bloque 2x2 en la esquina inferior derecha
matriz15[2:4, 2:4] = np.array([[99, 99], [99, 99]])
print("\nMatriz con bloque reemplazado:\n", matriz15)


Matriz con bloque reemplazado:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 99 99]
 [13 14 99 99]]
